USE ecommerce;

CREATE TABLE   ECOMMERCE.TR_ANDES_ORDER  AS
SELECT 
O.ID_ORDER, 
O.reference AS REFERENCIA,
C.COMPANY AS COMPANY,
C.ID_CUSTOMER ID_CUSTOMER, 
C.EMAIL AS EMAIL,
O.PAYMENT AS PAYMENT_TYPE,
sum(P.QUANTITY) CANT_PROD, 
SUM(O.TOTAL_PAID), 
SUM(O.TOTAL_PAID_REAL),  
O.DATE_UPD AS UPDATED_AT
FROM ECOMMERCE.ps_orders AS O 
LEFT JOIN ECOMMERCE.ps_customer AS C ON O.ID_CUSTOMER = C.ID_CUSTOMER
LEFT JOIN ECOMMERCE.ps_cart_product as P ON O.ID_CART = P.ID_CART 
GROUP BY 1,2
ORDER BY 1 DESC;
