USE ecommerce;

 CREATE TABLE ECOMMERCE.TR_ANDES_ORDER AS
SELECT 
    O.ID_ORDER, 
    O.reference AS REFERENCIA,
    C.COMPANY AS COMPANY,
    C.ID_CUSTOMER,
    C.EMAIL AS EMAIL,
    CI.id_city,
    CI.NAME,
    O.PAYMENT AS PAYMENT_TYPE,
    O.DATE_ADD AS DATE_ADD,
    SUM(P.QUANTITY) AS CANT_PROD, 
    SUM(O.TOTAL_PAID) AS TOTAL_PAID,
    SUM(O.TOTAL_PAID_REAL) AS TOTAL_PAID_REAL,
    O.DATE_UPD AS UPDATED_AT
FROM 
    ECOMMERCE.ps_orders AS O 
LEFT JOIN 
    ECOMMERCE.ps_customer AS C ON O.ID_CUSTOMER = C.ID_CUSTOMER
LEFT JOIN 
    ECOMMERCE.ps_cart_product AS P ON O.ID_CART = P.ID_CART 
LEFT JOIN 
	ECOMMERCE.ps_address AS A ON O.ID_CUSTOMER = A.ID_CUSTOMER
LEFT JOIN
	ECOMMERCE.ps_city AS CI ON A.id_city = CI.id_city
GROUP BY 
    1, 2, 3, 4, 5, 6, 7, 8, 9
ORDER BY 
    1 DESC;
